w = [0.98, 1.0, 0.94, 1.07, 1.02]
a = 0.22        # Параметры
b = 0.1         # системы
c = 8.5         #

k_elements = 5  # Число агентов
k = 3           # Число уравнений для одного агента (всегда 3)

radius = 3      # Радиус связи
T = 0.2         # Сила связи


plot_colors = [
    "blue",
    "orange",
    "green",
    "red",
    "indigo",
    "m",
    "purple",
    "gray",
    "olive",
    "pink",
    "black",
    "salmon",
    "tomato",
    "navy",
    "lime",
    "orchid",
    'crimson',
    'plum',
    'peru',
    'lightskyblue',
    'forestgreen',
    'tan',
    'coral',
    'goldenrod',
    'silver'
]

# Data paths
grid_experiments_path = './data/grid_experiments/'